set(_CATKIN_CURRENT_PACKAGE "jzhao_suture_simulation_ver31")
set(jzhao_suture_simulation_ver31_VERSION "0.3.0")
set(jzhao_suture_simulation_ver31_MAINTAINER "Murilo Marinho <murilo@nml.t.u-tokyo.ac.jp>")
set(jzhao_suture_simulation_ver31_PACKAGE_FORMAT "2")
set(jzhao_suture_simulation_ver31_BUILD_DEPENDS "sas_clock" "roscpp" "rospy")
set(jzhao_suture_simulation_ver31_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(jzhao_suture_simulation_ver31_BUILDTOOL_DEPENDS "catkin")
set(jzhao_suture_simulation_ver31_BUILDTOOL_EXPORT_DEPENDS )
set(jzhao_suture_simulation_ver31_EXEC_DEPENDS "roscpp" "rospy")
set(jzhao_suture_simulation_ver31_RUN_DEPENDS "roscpp" "rospy")
set(jzhao_suture_simulation_ver31_TEST_DEPENDS )
set(jzhao_suture_simulation_ver31_DOC_DEPENDS )
set(jzhao_suture_simulation_ver31_URL_WEBSITE "")
set(jzhao_suture_simulation_ver31_URL_BUGTRACKER "")
set(jzhao_suture_simulation_ver31_URL_REPOSITORY "")
set(jzhao_suture_simulation_ver31_DEPRECATED "")